"""AI factuality guard: does the output actually follow from the source?

Two independent signals per claim:

* **Semantic support** - cosine similarity between the claim embedding and the
  retrieved evidence, boosted when key terms overlap.
* **Numeric grounding** - every number in the claim must exist in the source.
  Fabricated figures are the most common and most damaging hallucination, so a
  number that is not in the evidence is treated as unsupported regardless of
  how well the sentence reads.
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field
from typing import Any

from ..config import get_settings
from .embeddings import embed
from .retrieval import RetrievedChunk
from .textutils import (
    NUMBER_RE,
    content_tokens,
    cosine_similarity,
    safe_snippet,
    split_sentences,
)

# Scaffolding that carries no claim of its own: markdown headings, the closing
# card and the generated footer's own label.
SKIP_LINE_RE = re.compile(
    r"^\s*(?:[-*•]\s*)?(?:#+\s|\[end card\]\s*$|title:?\s*$|\[Panel \d+\]\s*$)",
    re.IGNORECASE,
)

# A leading "[...]" tag: scene, panel, frame or beat markers. Everything the
# generator puts inside one is scaffolding, not a factual claim.
LEADING_TAG_RE = re.compile(r"^\[[^\]]{0,140}\]\s*")

# Field labels the generators prefix onto content lines. The label is
# scaffolding; the text after it is the claim and must still be checked.
FIELD_LABEL_RE = re.compile(
    r"^\s*(?:[-*•]\s*)?(?:"
    r"(?:stat|body|headline|title|subtitle|narration|caption|overlay|visual|on-screen text|"
    r"speaker note|body copy|key message|cta|action|summary|quote|statistic)\s*:\s*"
    r"|---\s*slide[^:]*:\s*"
    r")",
    re.IGNORECASE,
)

# Production metadata: commentary about the artefact, not assertions about the
# subject. A runtime in seconds or a "confidence" note is true by construction,
# so holding it to source grounding would report drift that does not exist.
METADATA_LINE_RE = re.compile(
    r"^\s*(?:confidence|total narration|narration time|duration|estimated duration|"
    r"runtime|total runtime|word count|character count|reading time|aspect ratio|"
    r"generated by|generated from|prepared by|produced by|source|every bullet traces)\b",
    re.IGNORECASE,
)

# "Stat: 412,000 (as stated in source)" asserts a figure and nothing else. It is
# verified numerically, not semantically, so it is kept out of the prose claims.
STAT_LINE_RE = re.compile(
    r"^\s*(?:[-*•]\s*)?(?:stat|statistic|key figure|figure)\s*:\s*(?P<value>.+)$",
    re.IGNORECASE,
)

BULLET_PREFIX_RE = re.compile(r"^\s*(?:[-*•‣▪●]|\d+[.)])\s+")

# Clip markers the generators add when a line is shortened for layout.
TRUNCATION_RE = re.compile(r"(?:\s*(?:…|\.\.\.)\s*)$")

UNSUPPORTED_MARKER = re.compile(r"not stated in source", re.IGNORECASE)


@dataclass
class ClaimCheck:
    text: str
    support: float
    supported: bool
    reason: str
    numbers: list[str] = field(default_factory=list)
    invented_numbers: list[str] = field(default_factory=list)


@dataclass
class FactualityReport:
    grounding_score: float
    verdict: str
    claims_total: int
    claims_supported: int
    claims_unsupported: list[dict[str, Any]] = field(default_factory=list)
    invented_numbers: list[str] = field(default_factory=list)
    coverage_note: str = ""
    method: str = "claim-level semantic support + numeric grounding"

    def as_dict(self) -> dict[str, Any]:
        return {
            "grounding_score": round(self.grounding_score, 4),
            "verdict": self.verdict,
            "claims_total": self.claims_total,
            "claims_supported": self.claims_supported,
            "claims_unsupported": self.claims_unsupported,
            "invented_numbers": self.invented_numbers,
            "coverage_note": self.coverage_note,
            "method": self.method,
        }


MIN_CLAIM_CHARS = 12


def normalise_claim_line(line: str) -> str:
    """Strip generator scaffolding, keeping the assertion itself.

    Infographic, storyboard and video formats put their content behind labels
    such as ``Body:`` or ``Narration:`` and bracketed scene tags. Those labels
    are layout, not claims - dropping the whole line (the previous behaviour)
    made the factuality gate report 0% grounding on perfectly grounded
    artefacts, so the label is removed and the remainder is what gets checked.
    """
    text = line.strip()
    text = LEADING_TAG_RE.sub("", text).strip()
    text = re.sub(r"^#+\s*", "", text).strip()
    text = FIELD_LABEL_RE.sub("", text).strip()
    return TRUNCATION_RE.sub("", text).strip()


def extract_claims(text: str, max_claims: int = 60) -> list[str]:
    """One claim per content line, with layout stripped.

    Line-based on purpose: re-splitting the artefact into sentences would glue
    neighbouring panels back together and hide which number belongs to which
    claim.
    """
    claims: list[str] = []
    for line in text.split("\n"):
        stripped = line.strip()
        if SKIP_LINE_RE.match(line) or METADATA_LINE_RE.match(stripped):
            continue
        if STAT_LINE_RE.match(stripped):
            continue
        claim = normalise_claim_line(line)
        if len(claim) < MIN_CLAIM_CHARS or BULLET_PREFIX_RE.match(claim):
            continue
        claims.append(claim)

    if not claims:
        # Layout-only artefact (a title card, say): fall back to sentences so a
        # genuinely empty check is not silently reported as fully grounded.
        for sentence in split_sentences(text):
            claim = normalise_claim_line(sentence)
            if len(claim) >= MIN_CLAIM_CHARS:
                claims.append(claim)
    return claims[:max_claims]


def _normalise_number(token: str) -> str:
    return re.sub(r"[,\s%]", "", token).rstrip(".").lower()


def _stat_assertions(text: str) -> list[ClaimCheck]:
    """Figure-only assertions from ``Stat:`` lines, pending numeric checking.

    Returned as unevaluated checks so a fabricated headline figure is reported
    in exactly the same way as a fabricated number in prose.
    """
    checks: list[ClaimCheck] = []
    for line in text.split("\n"):
        match = STAT_LINE_RE.match(line.strip())
        if not match:
            continue
        value = match.group("value").strip()
        numbers = [_normalise_number(n) for n in NUMBER_RE.findall(value)]
        checks.append(
            ClaimCheck(
                text=value,
                support=0.0,
                supported=False,
                reason="statistic pending numeric check",
                numbers=[n for n in numbers if n],
                invented_numbers=[],
            )
        )
    return checks


def _source_numbers(evidence: list[RetrievedChunk]) -> set[str]:
    numbers: set[str] = set()
    for result in evidence:
        for token in NUMBER_RE.findall(result.chunk.text):
            numbers.add(_normalise_number(token))
        # bare digit runs, so "1,200" in the source matches "1200" in output
        for token in re.findall(r"\d[\d,]*\.?\d*", result.chunk.text):
            numbers.add(_normalise_number(token))
    return numbers


def check_output(
    text: str,
    evidence: list[RetrievedChunk],
    min_score: float | None = None,
) -> FactualityReport:
    settings = get_settings()
    threshold = settings.grounding_min_score if min_score is None else min_score

    if not text.strip():
        return FactualityReport(
            grounding_score=0.0,
            verdict="empty",
            claims_total=0,
            claims_supported=0,
            coverage_note="No output produced.",
        )

    claims = extract_claims(text)
    pending_stats = _stat_assertions(text)
    if not claims and not pending_stats:
        return FactualityReport(
            grounding_score=1.0,
            verdict="no_claims",
            claims_total=0,
            claims_supported=0,
            coverage_note="Output contained no verifiable claims (layout-only artefact).",
        )

    evidence_vectors = [(r, r.chunk.embedding or []) for r in evidence]
    source_numbers = _source_numbers(evidence)
    evidence_token_sets = [set(content_tokens(r.chunk.text)) for r in evidence]

    results: list[ClaimCheck] = []

    for claim in claims:
        vector = embed(claim)
        claim_tokens = set(content_tokens(claim))
        best = 0.0
        verbatim = False
        for (_, ev_vector), token_set in zip(evidence_vectors, evidence_token_sets, strict=False):
            score = cosine_similarity(vector, ev_vector) if ev_vector else 0.0
            if claim_tokens and token_set:
                overlap = len(claim_tokens & token_set) / len(claim_tokens)
                score = 0.72 * score + 0.28 * overlap
                if claim_tokens <= token_set:
                    # Every content word of the claim occurs in one source chunk.
                    # Formats that clip lines to a character budget would
                    # otherwise be penalised for the clipping, so containment in
                    # the source counts as full support. Invented numbers are
                    # still rejected outright below.
                    score = max(score, 1.0)
                    verbatim = True
            best = max(best, score)

        numbers = [_normalise_number(n) for n in NUMBER_RE.findall(claim)]
        invented = [n for n in numbers if n and n not in source_numbers]

        if UNSUPPORTED_MARKER.search(claim):
            results.append(ClaimCheck(claim, 1.0, True, "explicit gap marker", numbers, []))
            continue
        if invented and settings.numeric_grounding_enabled:
            results.append(
                ClaimCheck(
                    claim,
                    best,
                    False,
                    "numeric value not present in retrieved source evidence",
                    numbers,
                    invented,
                )
            )
            continue

        supported = best >= threshold
        results.append(
            ClaimCheck(
                claim,
                best,
                supported,
                (
                    "claim text appears verbatim in retrieved evidence"
                    if verbatim
                    else "semantic support above threshold"
                )
                if supported
                else "weak semantic support",
                numbers,
                [],
            )
        )

    for stat in pending_stats:
        invented = [n for n in stat.numbers if n not in source_numbers]
        if not stat.numbers:
            # "Not stated in source" and friends: an honest gap, not a figure.
            results.append(
                ClaimCheck(stat.text, 1.0, True, "explicit gap marker", [], [])
            )
        elif invented and settings.numeric_grounding_enabled:
            results.append(
                ClaimCheck(
                    stat.text,
                    0.0,
                    False,
                    "statistic not present in retrieved source evidence",
                    stat.numbers,
                    invented,
                )
            )
        else:
            results.append(
                ClaimCheck(
                    stat.text,
                    1.0,
                    True,
                    "statistic matches a figure in the source",
                    stat.numbers,
                    [],
                )
            )

    supported_count = sum(1 for r in results if r.supported)
    grounding = supported_count / len(results)
    unsupported = [
        {
            "text": safe_snippet(r.text, 200),
            "support": round(r.support, 4),
            "reason": r.reason,
            "invented_numbers": r.invented_numbers,
        }
        for r in results
        if not r.supported
    ]
    invented_all = sorted({n for r in results for n in r.invented_numbers})

    if grounding >= 0.85:
        verdict = "grounded"
    elif grounding >= 0.6:
        verdict = "partially_grounded"
    elif grounding >= 0.35:
        verdict = "weakly_grounded"
    else:
        verdict = "ungrounded"

    if invented_all:
        verdict = "numeric_drift" if verdict == "grounded" else verdict

    return FactualityReport(
        grounding_score=grounding,
        verdict=verdict,
        claims_total=len(results),
        claims_supported=supported_count,
        claims_unsupported=unsupported[:20],
        invented_numbers=invented_all[:20],
        coverage_note=(
            f"{supported_count}/{len(results)} claims supported by retrieved evidence "
            f"(threshold {threshold:.2f})."
        ),
    )
